Repository api3dao/vitepress-docs, pull requests merged in 2023-05, with the labels that each got.

#447 content adjustments
  docs/reference/dapis/chains/index.md
  docs/reference/dapis/dapi-names.md
Labels: corrections, /reference, dAPIs

#450 20230504 dapi chains chain browser
  docs/reference/dapis/chains/chains-list.md
Labels: enhancement, dAPIs

#457 Clarify `sponsorWallet` language
  docs/guides/airnode/calling-an-airnode/index.md
  docs/reference/airnode/latest/concepts/sponsor.md
  docs/reference/airnode/latest/developers/requesters-sponsors.md
  docs/reference/airnode/next/concepts/sponsor.md
  docs/reference/airnode/next/developers/requesters-sponsors.md
Labels: enhancement, Airnode

#458 Clarify `sponsorWallet` language (#457)
  docs/guides/airnode/calling-an-airnode/index.md
  docs/reference/airnode/latest/concepts/sponsor.md
  docs/reference/airnode/latest/developers/requesters-sponsors.md
  docs/reference/airnode/next/concepts/sponsor.md
  docs/reference/airnode/next/developers/requesters-sponsors.md
Labels: enhancement, /reference, Airnode

#460 prettier format
  docs/.vitepress/frontmatterIds.json
Labels: corrections

#463 20230508 redirects
  docs/.vitepress/versions.json
  docs/_components/vitepress/NotFound.vue
  package.json
Labels: enhancement

#466 20230508 corrections minor and archive (#465)
  archives/.vitepress/versionsAirnodeLegacy.json
  docs/_components/vitepress/NotFound.vue
Labels: live-site

#456 ga4_tag
  docs/.vitepress/config.js
  yarn.lock
Labels: enhancement

#468 ga4_tag (#456)
  docs/.vitepress/config.js
  yarn.lock
Labels: live-site

#479 20230525 vitepress 1.0.0 beta.1
  .prettierignore
  docs/reference/dapis/sidebar.js
  package.json
  yarn.lock
Labels: enhancement

#486 Move /public root images to /public/img
  docs/.vitepress/config.js
  docs/.vitepress/theme/components/Market.vue
  docs/index.md
  docs/public/img/API3-Active.png
  docs/public/img/api3-inactive.png
  docs/public/img/beacons.svg
  docs/public/img/small-logo.png
  docs/public/styles/api3.css
Labels: enhancement
