Repository api3dao/vitepress-docs, pull requests merged in 2023-03, with the labels that each got.

#241 update dAPI guides
  archives/explore/dapis/why-power.md
  docs/explore/assets/images/00-a-What_are_dAPIs.png
  docs/explore/assets/images/00-b-What_are_dAPIs.png
  docs/explore/assets/images/01-API_Providers-why_power_dAPIs-Chain_overview.png
  docs/explore/assets/images/02-What_is_Airnode.png
  docs/explore/assets/images/03-Airnode_Pros_and_Cons.png
  docs/explore/assets/images/04-Airnode_Design_Philosophy.png
  docs/explore/assets/images/05-a-Configuration_Files-AWS.png
  docs/explore/assets/images/05-b-Configuration_Files-GCP.png
  docs/explore/assets/images/05-c-Configuration_Files-Container.png
  docs/explore/assets/images/06-a-API3_DAO-Op1.png
  docs/explore/assets/images/06-a-API3_DAO-Op2.png
  docs/explore/assets/images/06-a-API3_DAO-Op3.png
  docs/explore/assets/images/07-a-The_DAO_pool-Staking.png
  docs/explore/assets/images/07-b-The_DAO_pool-Token_Utilities.png
  docs/explore/assets/images/08-Inflationary_Rewards.png
  docs/explore/assets/images/09-Visual_that_communicates_how_a_self-funded_feed_works.png
  docs/explore/assets/images/10-Visual_that_communicates_how_a_managed_service_feed.png
  docs/explore/assets/images/11-Visual_that_communicates_the_process_of_sponsoring_a_byog_feed_using_the_market.png
  docs/explore/assets/images/12-Visual_that_communicates_self_funded_feeds_vs_managed_service_dAPIs.png
  docs/explore/assets/images/market-screenshot-march2023.png
  docs/explore/dapis/OEV.md
  docs/explore/dapis/how-are-dAPIs-maintained.md
  docs/explore/dapis/security-considerations.md
  docs/explore/dapis/service-coverage.md
  docs/explore/dapis/sponsor-dapis.md
  docs/explore/dapis/what-are-dapis.md
  docs/explore/dapis/why-use-dapis.md
  docs/explore/introduction/decentralized-apis.md
  docs/explore/introduction/market.md
  docs/explore/sidebar.js
  yarn.lock
Labels: /explore, dAPIs

#285 update dAPI guides (#241)
  archives/explore/dapis/why-power.md
  docs/explore/assets/images/00-a-What_are_dAPIs.png
  docs/explore/assets/images/00-b-What_are_dAPIs.png
  docs/explore/assets/images/01-API_Providers-why_power_dAPIs-Chain_overview.png
  docs/explore/assets/images/02-What_is_Airnode.png
  docs/explore/assets/images/03-Airnode_Pros_and_Cons.png
  docs/explore/assets/images/04-Airnode_Design_Philosophy.png
  docs/explore/assets/images/05-a-Configuration_Files-AWS.png
  docs/explore/assets/images/05-b-Configuration_Files-GCP.png
  docs/explore/assets/images/05-c-Configuration_Files-Container.png
  docs/explore/assets/images/06-a-API3_DAO-Op1.png
  docs/explore/assets/images/06-a-API3_DAO-Op2.png
  docs/explore/assets/images/06-a-API3_DAO-Op3.png
  docs/explore/assets/images/07-a-The_DAO_pool-Staking.png
  docs/explore/assets/images/07-b-The_DAO_pool-Token_Utilities.png
  docs/explore/assets/images/08-Inflationary_Rewards.png
  docs/explore/assets/images/09-Visual_that_communicates_how_a_self-funded_feed_works.png
  docs/explore/assets/images/10-Visual_that_communicates_how_a_managed_service_feed.png
  docs/explore/assets/images/11-Visual_that_communicates_the_process_of_sponsoring_a_byog_feed_using_the_market.png
  docs/explore/assets/images/12-Visual_that_communicates_self_funded_feeds_vs_managed_service_dAPIs.png
  docs/explore/assets/images/market-screenshot-march2023.png
  docs/explore/dapis/OEV.md
  docs/explore/dapis/how-are-dAPIs-maintained.md
  docs/explore/dapis/security-considerations.md
  docs/explore/dapis/service-coverage.md
  docs/explore/dapis/sponsor-dapis.md
  docs/explore/dapis/what-are-dapis.md
  docs/explore/dapis/why-use-dapis.md
  docs/explore/introduction/decentralized-apis.md
  docs/explore/introduction/market.md
  docs/explore/sidebar.js
  yarn.lock
Labels: live-site

#289 --detach usage
  docs/guides/airnode/deploy-airnode/deploy-container/index.md
  docs/reference/airnode/latest/docker/client-image.md
Labels: enhancement, /guides, /reference

#292 deploymentId was noted as an address
  docs/reference/airnode/latest/docker/deployer-image.md
Labels: corrections, /reference, Airnode

#293 deploymentId was noted as an address (#292)
  docs/reference/airnode/latest/docker/deployer-image.md
Labels: live-site

#295 Using stage endpoint until prod is fixed
  docs/_components/reference/dapis/chains/ChainsList.vue
Labels: enhancement, /reference

#296 Using stage endpoint until prod is fixed (#295)
  docs/_components/reference/dapis/chains/ChainsList.vue
Labels: live-site

#297 List two possible outcomes for rrp
  docs/reference/airnode/latest/concepts/request.md
Labels: corrections, Airnode

#298 List two possible outcomes for rrp (#297)
  docs/reference/airnode/latest/concepts/request.md
Labels: live-site

#303 This represents a simplification of /reference/dapis
  archives/reference/dapis/best-practices.md
  archives/reference/dapis/functions/data-feed-id-to-reader-to-whitelist-status.md
  archives/reference/dapis/functions/index.md
  archives/reference/dapis/functions/read-data-feed-value-with-dapi-name.md
  archives/reference/dapis/functions/read-data-feed-value-with-id.md
  archives/reference/dapis/functions/read-data-feed-with-dapi-name.md
  archives/reference/dapis/functions/read-data-feed-with-id.md
  archives/reference/dapis/functions/reader-can-read-datafeed.md
  docs/explore/dapis/what-are-dapis.md
  docs/reference/dapis/assets/diagrams/.$beacons.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$beacons.drawio.dtmp
  docs/reference/dapis/assets/diagrams/.$dapi-beacons.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$dapp-beacon.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$dapp-beacon.drawio.dtmp
  docs/reference/dapis/assets/diagrams/.$proxy.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$why-power-beacons.drawio.bkp
  docs/reference/dapis/assets/diagrams/beacons.drawio
  docs/reference/dapis/assets/diagrams/dapi-beacons.drawio
  docs/reference/dapis/assets/diagrams/proxy.drawio
  docs/reference/dapis/assets/images/beacons.png
  docs/reference/dapis/assets/images/dapi-beacons.png
  docs/reference/dapis/assets/images/monitor.png
  docs/reference/dapis/assets/images/proxy.png
  docs/reference/dapis/assets/images/why-power-beacons.png
  docs/reference/dapis/chains.md
  docs/reference/dapis/dapi-names.md
  docs/reference/dapis/index.md
  docs/reference/dapis/schemes.md
  docs/reference/dapis/sidebar.js
Labels: live-site

#316 Merge of new dAPI explore and reference material
  docs/explore/assets/images/00-Smart_contracts_requires_real_world_data_to_provide_meaningful_services.png
  docs/explore/assets/images/02-b-First_vs_Third_party_oracles-Descentralized_API_(dAPI).png
  docs/explore/assets/images/API3_market_march2023.png
  docs/explore/assets/images/API3_market_march2023_v1.png
  docs/explore/assets/images/API_use_cases_intro.png
  docs/explore/assets/images/Managed_dAPI_visual.png
  docs/explore/assets/images/Sponsoring_a_feed_overview.png
  docs/explore/assets/images/dAPI_explainer.png
  docs/explore/assets/images/dAPI_explainer_advanced.png
  docs/explore/assets/images/first-party-aggregated.png
  docs/explore/assets/images/self_funded_market_process_notext.png
  docs/explore/dapis/OEV.md
  docs/explore/dapis/security-considerations.md
  docs/explore/dapis/service-coverage.md
  docs/explore/dapis/what-are-dapis.md
  docs/explore/introduction/decentralized-apis.md
  docs/explore/introduction/first-party.md
  docs/explore/introduction/index.md
  docs/explore/introduction/market.md
  docs/reference/dapis/assets/diagrams/.$beacons-airnode.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$beacons.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$beacons.drawio.dtmp
  docs/reference/dapis/assets/diagrams/beacons-airnode.drawio
  docs/reference/dapis/assets/diagrams/beacons.drawio
  docs/reference/dapis/assets/images/beacons-airnode.png
  docs/reference/dapis/assets/images/beacons.png
  docs/reference/dapis/understand/index.md
  yarn.lock
Labels: live-site

#322 20230317 frontmatter search
  docs/.vitepress/frontmatterIds.json
  docs/explore/dapis/OEV.md
  docs/explore/dapis/how-are-dAPIs-maintained.md
  docs/reference/dapis/understand/read-dapis.md
Labels: corrections

#336 Display only Api3Server.sol and not DapiServer.sol
  docs/_components/reference/dapis/chains/ChainsItem.vue
  docs/_components/reference/dapis/chains/ChainsList.vue
Labels: /reference, dAPIs

#340 20230321 updates to `/dev`
  docs/.vitepress/versionsAirnodeLegacy.json
  docs/dev/docsets.md
  docs/dev/sidebar.js
  docs/dev/tabs.md
  docs/dev/versioning.md
  firebase.json
Labels: enhancement

#355 illustrations_formatting
  docs/explore/airnode/how-does-airnode-work.md
  docs/explore/airnode/unlocking-real-world-data.md
  docs/explore/airnode/what-is-airnode.md
  docs/explore/airnode/why-first-party-oracles.md
  docs/explore/assets/images/03-solving_the_API_connectivity_problem_Airnode (1).png
  docs/explore/assets/images/03-solving_the_API_connectivity_problem_Airnode.png
  docs/explore/assets/images/05-How_Airnode_works.png
  docs/explore/assets/images/RNG_types.png
  docs/explore/dao-members/dao-pool.md
  docs/explore/dao-members/index.md
  docs/explore/dao-members/rewards.md
  docs/explore/qrng/index.md
Labels: /explore

#366 Simple changes to reflect modified development practices
  docs/dev/firebase.md
  docs/dev/frontmatter.md
  docs/dev/index.md
  docs/dev/navboxes.md
  docs/dev/rosetta.md
Labels: corrections
