Repository api3dao/vitepress-docs, pull requests merged in 2023-04, with the labels that each got.

#370 20230404 upgrades corrections
  docs/dev/assets/images/ssr-cloudflare.png
  docs/dev/firebase.md
  docs/dev/flexsearch.md
  docs/dev/sidebar.js
  docs/dev/ssr.md
  docs/explore/introduction/first-party.md
  package.json
Labels: corrections, enhancement

#372 Mostly simple corrections and upgrade watch pack
  docs/dev/assets/images/ssr-cloudflare.png
  docs/dev/firebase.md
  docs/dev/flexsearch.md
  docs/dev/sidebar.js
  docs/dev/ssr.md
  docs/explore/introduction/first-party.md
  docs/reference/dapis/assets/diagrams/.$proxy-self-funded.drawio.bkp
  docs/reference/dapis/assets/diagrams/.$proxy-self-funded.drawio.dtmp
  docs/reference/dapis/assets/diagrams/proxy-self-funded.drawio
  docs/reference/dapis/assets/images/proxy-self-funded.png
  package.json
Labels: live-site

#373 Minor grammar on ssr
  docs/dev/ssr.md
Labels: corrections

#374 Minor grammar on ssr (#373)
  docs/dev/ssr.md
Labels: live-site

#376 `fulfillmentGasLimit` changes move to `v0.12`
  docs/reference/airnode/latest/chain-idiosyncrasies.md
  docs/reference/airnode/latest/deployment-files/config-json.md
Labels: corrections, /reference, Airnode

#377 20230404 dev minor corrections
  docs/dev/index.md
  docs/dev/rosetta.md
  docs/dev/ssr.md
Labels: corrections

#378 `fulfillmentGasLimit` and minor doc set `/dev` changes
  docs/dev/index.md
  docs/dev/rosetta.md
  docs/dev/ssr.md
  docs/reference/airnode/latest/chain-idiosyncrasies.md
  docs/reference/airnode/latest/deployment-files/config-json.md
Labels: live-site

#391 20230411 corrections
  docs/explore/dapis/what-are-dapis.md
  docs/guides/airnode/monorepo-examples.md
Labels: corrections

#401 Change frontmatter pageHeader to v2.0
  docs/reference/ois/latest/processing.md
Labels: corrections, OIS, /reference

#405 Describe enforced endpointId derivation scheme
  docs/reference/airnode/latest/concepts/endpoint.md
  docs/reference/airnode/latest/deployment-files/config-json.md
  docs/reference/airnode/latest/packages/admin-cli.md
  docs/reference/airnode/next/concepts/endpoint.md
  docs/reference/airnode/next/deployment-files/config-json.md
  docs/reference/airnode/next/packages/admin-cli.md
Labels: enhancement, /reference, Airnode

#413 Vitepress 72
  docs/_components/vitepress/VPFlyout.vue
  docs/_components/vitepress/VPNavBar.vue
  docs/_components/vitepress/VPNavBarTitle.vue
  docs/reference/airnode/latest/index.md
  docs/reference/airnode/next/index.md
  docs/reference/qrng/chains.md
  package.json
  yarn.lock
Labels: enhancement

#425 20230425 legacy versions
  archives/_components/explore/blog-posts.json
  docs/.vitepress/theme/components/SidebarHeader.vue
  docs/.vitepress/versions-legacy.json
  docs/_components/reference/VersionPicklist.vue
  docs/explore/airnode/pros-and-cons.md
  docs/explore/introduction/index.md
  docs/reference/airnode/latest/versions.md
  docs/reference/airnode/next/versions.md
Labels: OIS, enhancement, /reference, Airnode

#426 20230425 legacy versions (#425)
  archives/_components/explore/blog-posts.json
  docs/.vitepress/theme/components/SidebarHeader.vue
  docs/.vitepress/versions-legacy.json
  docs/_components/reference/VersionPicklist.vue
  docs/explore/airnode/pros-and-cons.md
  docs/explore/introduction/index.md
  docs/reference/airnode/latest/versions.md
  docs/reference/airnode/next/versions.md
Labels: live-site

#434 Added function outputFileSize(path)
  libs/flexBuildIndexes.js
Labels: enhancement

#438 435 create three flex indexes
  archives/_components/search/SearchBtn-20230428.vue
  archives/_components/search/SearchResults-20230428.vue
  archives/_components/search/indexes-all.js
  archives/_components/search/indexes-latest.js
  docs/_components/SearchHighlight.vue
  docs/_components/search/SearchBtn.vue
  docs/_components/search/SearchResults.vue
  docs/_components/search/indexes-all.js
  docs/_components/search/indexes-latest.js
  docs/public/img/circle-loading-gif.webp
  docs/public/indexes/all-dev/cfg.json
  docs/public/indexes/all-dev/ctx.json
  docs/public/indexes/all-dev/reg.json
  docs/public/indexes/all/reg.json
  libs/flexBuildIndexes.js
Labels: enhancement, v0.12

#439 Bring the animated gif to life.
  docs/_components/search/SearchBtn.vue
Labels: enhancement, v0.12

#440 Add all versions checkbox
  docs/_components/search/SearchBtn.vue
  docs/_components/search/SearchResults.vue
Labels: enhancement, v0.12

#441 Flex search ready for multiple Airnode/OIS versions
  archives/_components/search/SearchBtn-20230428.vue
  archives/_components/search/SearchResults-20230428.vue
  archives/_components/search/indexes-all.js
  archives/_components/search/indexes-latest.js
  docs/_components/SearchHighlight.vue
  docs/_components/search/SearchBtn.vue
  docs/_components/search/SearchResults.vue
  docs/_components/search/indexes-all.js
  docs/_components/search/indexes-latest.js
  docs/public/img/circle-loading-gif.webp
  docs/public/indexes/all-dev/cfg.json
  docs/public/indexes/all-dev/ctx.json
  docs/public/indexes/all-dev/reg.json
  docs/public/indexes/all/reg.json
  libs/flexBuildIndexes.js
Labels: live-site
